In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\andre\Teste de Hipótese - Brasileirão\Dados FBREF Brasileirão - Série B -2023.csv")

In [3]:
df

,Unnamed: 0,Date,Home Team,Score,Away Team
0,0,2023-04-14,Guarani,4–1,Avaí
1,1,2023-04-15,Vila Nova,2–1,Grêmio Novorizontino
2,2,2023-04-15,Sampaio Corrêa,3–3,Atl Goianiense
3,3,2023-04-15,Mirassol Futebol Clube,1–0,Chapecoense
4,4,2023-04-15,Juventude,1–2,Botafogo (SP)
...,...,...,...,...,...
375,419,2023-11-25,Atl Goianiense,3–0,Guarani
376,420,2023-11-25,Grêmio Novorizontino,2–0,Criciúma
377,421,2023-11-25,Avaí,0–0,Ituano
378,422,2023-11-25,Tombense Futebol Clube,0–1,Mirassol Futebol Clube
379,423,2023-11-25,Ceará,1–3,Juventude

In [4]:
df.insert(0, 'Número Jogo', range(1, 381))

In [5]:
df.reset_index(drop=True, inplace=True)

In [6]:
df.set_index('Número Jogo',inplace=True)

In [7]:
df = df.drop('Unnamed: 0', axis = 1)

In [8]:
df

                   Date               Home Team Score               Away Team
Número Jogo
1            2023-04-14                 Guarani   4–1                    Avaí
2            2023-04-15               Vila Nova   2–1    Grêmio Novorizontino
3            2023-04-15          Sampaio Corrêa   3–3          Atl Goianiense
4            2023-04-15  Mirassol Futebol Clube   1–0             Chapecoense
5            2023-04-15               Juventude   1–2           Botafogo (SP)
...                 ...                     ...   ...                     ...
376          2023-11-25          Atl Goianiense   3–0                 Guarani
377          2023-11-25    Grêmio Novorizontino   2–0                Criciúma
378          2023-11-25                    Avaí   0–0                  Ituano
379          2023-11-25  Tombense Futebol Clube   0–1  Mirassol Futebol Clube
380          2023-11-25                   Ceará   1–3               Juventude

[380 rows x 4 columns]

In [9]:
# Substituir o caractere de traço por hífen para garantir uma separação correta
df['Score'] = df['Score'].str.replace('–', '-')

# Dividir a coluna "score" em duas colunas separadas para gols mandante e visitante
df[['Gols_Mandante', 'Gols_Visitante']] = df['Score'].str.split('-', expand=True).astype(int)

# Calcular pontos para mandante e visitante
def calcular_pontos(row):
    if row['Gols_Mandante'] > row['Gols_Visitante']:
        return pd.Series({'Pontos_Mandante': 3, 'Pontos_Visitante': 0})
    elif row['Gols_Mandante'] < row['Gols_Visitante']:
        return pd.Series({'Pontos_Mandante': 0, 'Pontos_Visitante': 3})
    else:
        return pd.Series({'Pontos_Mandante': 1, 'Pontos_Visitante': 1})

# Aplicar a função para calcular os pontos
df[['Pontos_Mandante', 'Pontos_Visitante']] = df.apply(calcular_pontos, axis=1)

In [10]:
df

,Date,Home Team,Score,Away Team,Gols_Mandante,Gols_Visitante,Pontos_Mandante,Pontos_Visitante
Número Jogo,,,,,,,,
1,2023-04-14,Guarani,4-1,Avaí,4,1,3,0
2,2023-04-15,Vila Nova,2-1,Grêmio Novorizontino,2,1,3,0
3,2023-04-15,Sampaio Corrêa,3-3,Atl Goianiense,3,3,1,1
4,2023-04-15,Mirassol Futebol Clube,1-0,Chapecoense,1,0,3,0
5,2023-04-15,Juventude,1-2,Botafogo (SP),1,2,0,3
...,...,...,...,...,...,...,...,...
376,2023-11-25,Atl Goianiense,3-0,Guarani,3,0,3,0
377,2023-11-25,Grêmio Novorizontino,2-0,Criciúma,2,0,3,0
378,2023-11-25,Avaí,0-0,Ituano,0,0,1,1
379,2023-11-25,Tombense Futebol Clube,0-1,Mirassol Futebol Clube,0,1,0,3
380,2023-11-25,Ceará,1-3,Juventude,1,3,0,3

In [11]:
df['Home Team'].unique()

array(['Guarani', 'Vila Nova', 'Sampaio Corrêa', 'Mirassol Futebol Clube',
       'Juventude', 'Ituano', 'Criciúma', 'Londrina', 'Vitória',
       'Atl Goianiense', 'Botafogo (SP)', 'Tombense Futebol Clube',
       'Avaí', 'Grêmio Novorizontino', 'Ceará', 'Ponte Preta',
       'Chapecoense', 'ABC', 'CRB', 'Sport Recife'], dtype=object)

In [12]:
times_analisados = ['Ceará']
# Dicionário para armazenar os DataFrames de cada time
jogos_times = {}

# Iterar sobre os times
for time in times_analisados:
    # Filtrar os jogos em que o time é mandante ou visitante
    jogos_time = df[(df['Home Team'] == time) | (df['Away Team'] == time)]
    
    # Salvar o DataFrame do time no dicionário
    jogos_times[time] = jogos_time

In [13]:
# Separando os dataframes de cada time

jogos_ceara = jogos_times['Ceará'].copy()

In [14]:
jogos_ceara['Técnico'] = ''

In [15]:
# Converter a coluna "Date" para o formato datetime
jogos_ceara['Date'] = pd.to_datetime(jogos_ceara['Date'])

# Definir os intervalos de datas para cada técnico
gustavo_morinigo_periodo = (pd.to_datetime('2022-11-22'), pd.to_datetime('2023-04-24'))
eduardo_barroca_periodo = (pd.to_datetime('2023-04-24'), pd.to_datetime('2023-06-28'))
guto_ferreira_periodo = (pd.to_datetime('2023-06-29'), pd.to_datetime('2023-08-29'))
vagner_mancini_periodo = (pd.to_datetime('2023-08-30'), pd.to_datetime('2024-04-21'))

# Definir uma função para atribuir o técnico com base na data do jogo
def atribuir_tecnico(data):
    if gustavo_morinigo_periodo[0] <= data <= gustavo_morinigo_periodo[1]:
        return 'Gustavo Morinigo'
    elif eduardo_barroca_periodo[0] <= data <= eduardo_barroca_periodo[1]:
        return 'Eduardo Barroca'
    elif guto_ferreira_periodo[0] <= data <= guto_ferreira_periodo[1]:
        return 'Guto Ferreira'
    elif vagner_mancini_periodo[0] <= data <= vagner_mancini_periodo[1]:
        return 'Vagner Mancini'
    else:
        return 'Técnico Interino'

# Aplicar a função para atribuir o técnico com base na data do jogo
jogos_ceara['Técnico'] = jogos_ceara['Date'].apply(atribuir_tecnico)

In [16]:
jogos_ceara.index = range(1,39)
jogos_ceara = jogos_ceara.rename_axis('Rodada')

In [17]:
# Unificando a coluna da pontuação do time na partida, independente se foi casa ou fora

jogos_ceara['Pontuação Partida'] = jogos_ceara.apply(lambda row: row['Pontos_Mandante'] if row['Home Team'] == 'Ceará' else row['Pontos_Visitante'], axis=1)

In [18]:
jogos_ceara = jogos_ceara.drop(["Gols_Mandante", 'Gols_Visitante','Pontos_Mandante', 'Pontos_Visitante', 'Gols_Mandante', 'Gols_Visitante'], axis=1)

In [19]:
jogos_ceara.to_csv("Jogos Ceará.csv")

In [20]:
# Utilizando a coluna de técnicos como referência, tirar a média de pontos feitos nas rodadas de mesmo técnico
# e o desvio padrão da média durante o período do técnico.
# Fazer a mesma coisa com xG, utilizando termos xG A favor e xG Contra
# Salvar um DF com os nomes dos técnicos na primeira coluna e os seguintes dados na primeira linha: Número de jogos desse técnico, pontuacao_media, desvio_padrão_media_pontuação, xG_aFavor_medio, desvio_padrao_xGaFavor, xG_Contra_medio, desvio_padrao_xGaFavor

In [21]:
# Ceará
# Obtendo a ordem original dos técnicos
jogos_ceara.dropna(how='any', inplace=True)
jogos_ceara = jogos_ceara[jogos_ceara['Técnico'] != 'Técnico Interino']
jogos_ceara = jogos_ceara[jogos_ceara['Técnico'] != 'Gustavo Morinigo'] # Exclusão pois são pouquíssimos dados (2 jogos e 2 derrotas)
ordem_tecnicos = jogos_ceara['Técnico'].unique()

# Criando uma categoria ordenada com base na ordem original dos técnicos
categoria_tecnicos = pd.Categorical(jogos_ceara['Técnico'], categories=ordem_tecnicos, ordered=True)

# Agrupando os dados pelo técnico usando a categoria ordenada
tecnico_agrupado = jogos_ceara.groupby(categoria_tecnicos)

# Calcular as estatísticas para os jogos em que a equipe é tanto a equipe da casa quanto a equipe visitante
pontos_media = tecnico_agrupado['Pontuação Partida'].mean()
pontos_desvio_padrao = tecnico_agrupado['Pontuação Partida'].std()

# Contar o número de jogos para cada técnico
num_jogos = tecnico_agrupado.size()

# Criar um DataFrame com os resultados
resultados = pd.DataFrame({
    'Número de jogos': num_jogos,
    'Pontuação média': pontos_media,
    'Desvio padrão da média de pontos': pontos_desvio_padrao,
})

# Salvar os resultados em um arquivo CSV
resultados.to_csv('Tabela Médias Treinadores - Ceará.csv')

C:\Users\andre\AppData\Local\Temp\ipykernel_15984\3771532387.py:12: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tecnico_agrupado = jogos_ceara.groupby(categoria_tecnicos)

In [22]:
resultados

,Número de jogos,Pontuação média,Desvio padrão da média de pontos
Eduardo Barroca,12,1.750000,1.356801
Guto Ferreira,11,1.272727,1.190874
Vagner Mancini,13,1.153846,1.344504